name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run: npm run build

    - name: Deploy with gh-pages
      run: |
        echo ${GITHUB_REPOSITORY}
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -d dist -b slate -e source -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


  


