name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run: npm run build

    # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: slate
        FOLDER: dist
        TARGET_DIR: source
        CLEAR_GLOBS_FILE: .globs
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


  


